alias STAN='cd Sandboxes/THeApp/'

alias DOCKER_CODING='cd ~/Sandboxes/DockerSandbox'
alias UNREAL_CODING='cd ~/Sandboxes/UnrealEngine'
alias ANDROID_CODING='cd ~/Sandboxes/AndroidStudioDocker'

alias DISABLE_HIBERNATION='sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target'
alias ENABLE_HIBERNATION='sudo systemctl unmask sleep.target suspend.target hibernate.target hybrid-sleep.target'

alias ast='atuin stats'

alias navi='~/Sandboxes/navi_men/src/navi_men.bash ~/Sandboxes/navi_men/configs/navi_men_git.json'
