# shellcheck disable=2148
#
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=
HISTFILESIZE=

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r "${HOME}/.dircolors" && ( eval "$(dircolors -b "${HOME}"/.dircolors)" || eval "$(dircolors -b)" )
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -ahlF'
alias la='ls -Ah'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'


#
# @brief get the real location after resolving all links
#
# @params arg1 file/link/directory location to be resolved
# @return real location of file/link/directory passed in as first argument
#
get_real_location()
{
    if [[ "$#" -ne "1" ]]
    then
        echo "Error: function get_real_location expects exactly one argument!"
        exit 1
    fi
    SOURCE="$1"

    TMP_DIR=$( cd -- "$( dirname -- "${SOURCE}" )" &> /dev/null && pwd )
    while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
        TMP_DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
        SOURCE=$(readlink "$SOURCE")
        [[ $SOURCE != /* ]] && SOURCE=$TMP_DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
    done
    TMP_DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

    echo "${TMP_DIR}"
}

BRC_LOCATION=$( get_real_location "${BASH_SOURCE[0]}" )

# Alias definitions.
# You may want to put all your additions into a separate file like
#~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f "${BRC_LOCATION}/bash_aliases" ]; then
    # shellcheck source=/home/han/.dot_files/src/configs/bash/bash_aliases
    . "${BRC_LOCATION}/bash_aliases"
fi

if [ -f "${BRC_LOCATION}/bash_functions.sh" ]; then
    # shellcheck source=/home/han/.dot_files/src/configs/bash/bash_functions.sh
    . "${BRC_LOCATION}/bash_functions.sh"
fi



# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/completion ]; then
    # shellcheck disable=1091
    . /usr/share/bash-completion/completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

#complete -W "\`grep -oE '^[a-zA-Z0-9_.-]+:([^=]|$)' ?akefile | grep -v \".PHONY\" |  sed 's/[^a-zA-Z0-9_.-]*$//'\`" make

function followMakefile() {
  grep -oE '^[a-zA-Z0-9_.-]+[\/]*[a-zA-Z0-9_.-]+:([^=]|$)' ./?akefile | sed 's/[^a-zA-Z0-9_.-]*$//'

  # shellcheck disable=2013
  for x in $(grep -E '^include' ./?akefile | sed 's/include //')
  do
    grep -oE '^[a-zA-Z0-9_.-]+[\/]*[a-zA-Z0-9_.-]+:([^=]|$)' "${x}"  | grep -v "PHONY" | sed 's/[^a-zA-Z0-9_.-]*$//'
  done
}
complete -W "\`followMakefile\`" make

#function recurseMakefile() {
#  # First, look for any targets here - then look for includes and recurse
#  grep -oE '^[a-zA-Z0-9_.-]+:([^=]|$)' $1 | sed 's/[^a-zA-Z0-9_.-]*$//' | grep -v '.phony'
#  for x in $(grep -E '^include' $1 | sed -e 's/include //' -e 's/(/{/' -e 's/)/}/')
#  do
#    # Use envsubst to force variable name expansion
#    recurseMakefile "$(echo "$x" | envsubst)"
#  done
#}
#complete -W "\$(recurseMakefile ?akefile)" make


if [ -f /usr/share/bash-completion/completions/git ]
then
  source /usr/share/bash-completion/completions/git
fi

#source /opt/ros/melodic/setup.bash
#export ROS_HOSTNAME=NANZ88
#export ROS_MASTER_URI=http://NANZ88:11311/
export LC_NUMERIC="en_US.UTF-8"

eval "$(dircolors)"

export LESS='--quit-if-one-screen --ignore-case --LONG-PROMPT --RAW-CONTROL-CHARS --HILITE-UNREAD --tabs=4 --no-init --window=-4'
alias man='MANWIDTH=$(expr $COLUMNS - 1) man'

# Set colors for less. Borrowed from https://wiki.archlinux.org/index.php/Color_output_in_console#less .
export LESS_TERMCAP_mb=$'\E[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\E[1;36m'     # begin blink
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_so=$'\E[01;44;33m' # begin reverse video
export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline

unalias ls
unalias ll
unalias l
if ls --color -d . >/dev/null 2>&1; then  # GNU ls
  export COLUMNS  # Remember columns for subprocesses.
  eval "$(dircolors)"
  function ls {
    command ls -F -h --color=always -v --author --time-style=long-iso -C "$@" | less -R -X -F
  }
  alias ll='ls -l'
  alias l='ls -l -a'
fi

alias ls='ls -F -h --color=always -v --author --time-style=long-iso'
alias ll='ls -hl'
alias l='ls -hl -a'


# source /usr/share/doc/fzf/examples/completion.bash
# source /usr/share/doc/fzf/examples/key-bindings.bash
source "${HOME}/.atuin/bin/env"

if [ -f "${HOME}/.bash-preexec.sh" ]
then
  # well
  source "${HOME}/.bash-preexec.sh"
  eval "$(atuin init bash --disable-up-arrow)"
  atuin import bash >/dev/null 2>&1
fi


#export PATH=${HOME}/.navi:$PATH
#navi start
#eval "$(navi widget bash)"

create_bash_intro

